name: Build C Program

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List directory contents for debugging
      run: ls -R  # This will list the directory structure for debugging

    - name: Compile C code
      run: |
        gcc my_project/header.c my_project/main.c -o c_program
      continue-on-error: false  # Ensures the workflow fails if compilation fails

    - name: Upload compiled binary
      uses: actions/upload-artifact@v3
      with:
        name: compiled-program
        path: ./c_program
